spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
  batch:
    initialize-schema: always
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
#        default_batch_fetch_size: 500

logging:
  level:
    org.hibernate.SQL: debug
  config: classpath:log4j2.yml